#!/usr/bin/python



def partitionIdList(id):
    partitionTypes = {
        "00":"Empty partition entry",
        "01":"FAT32",
        "02":"XENIX root",
        "03":"XENIX usr",
        "04":"FAT16 <32M",
        "05":"Extended boot record",
        "06":"FAT16",
        "07":"HPFS/NTFS",
        "08":"AIX",
        "09":"AIX bootable",
        "0a":"OS/2 Boot Manage",
        "0b":"WIN95 FAT32 ",
        "0c":"WIN95 FAT32",
        "0e":"WIN95 FAT16",
        "0f":"WIN95 Extended (>8GB)",
        "10":"OPUS",
        "11":"Hidden FAT12",
        "12":"Compaq diagnost",
        "14":"Hidden FAT16<32GB",
        "16":"Hidden FAT16",
        "17":"Hidden HPFS/NTFS",
        "18":"AST Windows swap",
        "1b":"Hidden FAT32",
        "1c":"Hidden FAT32 partition (using LBA-mode INT 13 extensions)",
        "1e":"Hidden LBA VFAT partition",
        "24":"NEC DOS",
		"27":"D2D eRecovery",
        "3c":"Partition Magic",
        "40":"Venix 80286",
        "41":"PPC Prep Boot",
        "42":"SFS",
        "4d":"QNX4.x",
        "4e":"QNX4.x 2nd part",
        "4f":"QNX4.x 3rd part",
        "50":"Ontrack DM",
        "51":"Ontrack DM6 Aux",
        "52":"CP/M",
        "53":"Ontrack DM6 Aux",
        "54":"Ontrack DM6",
        "55":"EZ-Drive",
        "56":"Golden Bow",
        "5c":"priam Edisk",
        "61":"SpeedStor",
        "63":"GNU HURD or Sys",
        "64":"Novell Netware",
        "65":"Novell Netware",
        "70":"Disk Secure Mult",
        "75":"PC/IX",
        "80":"Old Minix",
        "81":"Minix/Old Linux",
        "82":"Linux swap",
        "83":"Linux",
        "84":"OS/2 hidden C:",
        "85":"Linunx extended",
        "86":"NTFS volume set",
        "87":"NTFS volume set",
        "93":"Amoeba",
        "94":"Amoeba BBT",
        "a0":"IBM Thinkpad hidden",
        "a5":"BSD/386",
        "a6":"OpenBSD",
        "a7":"NextStep",
        "b7":"BSDI fs",
        "b8":"BSDI swap",
        "be":"Solaris boot partition",
        "c0":"DR-DOS/Novell DOS secured partition",
        "c1":"DRDOS/sec",
        "c4":"DRDOS/sec",
        "c6":"DRDOS/sec",
        "c7":"Syrinx",
        "db":"CP/M/CTOS",
        "de":"FAT16 utility/diagnostic partition(DELL)",
        "e1":"DOS access",
        "e3":"DOS R/O",
        "e4":"SpeedStor",
        "eb":"BeOS fs",
        "f1":"SpeedStor",
        "f2":"DOS 3.3+ secondary partition",
        "f4":"SpeedStor",
        "fe":"LAN step",
        "ff":"BBT",
    }
    return partitionTypes[id]

